services:
  - type: web
    name: sistema-bancario
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn sistema_bancario.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-bancario-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: sistema-bancario-db
    plan: free
